# Generated by Django 3.2.3 on 2021-07-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('nama_ketua', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('no_telepon', models.CharField(max_length=100)),
                ('instansi', models.CharField(max_length=100)),
                ('prodi_ketua', models.CharField(max_length=100)),
                ('nama_anggota', models.CharField(max_length=100)),
                ('prodi_anggota', models.CharField(max_length=100)),
                ('subtema', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
